name: quranmemo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  # Database Lokal Untuk Surah, Ayat, Qari
  sqflite: ^2.3.0      
  path: ^1.9.0     

  flutter:
    sdk: flutter

  dio : ^5.3.2

  font_awesome_flutter: ^10.4.0
  # Font Arabic
  arabic_font: ^0.0.9
  
  # API Calls
  http: ^1.1.0
  
  # Icon Islamic
  flutter_islamic_icons: ^1.0.0
  # Caching gambar
  cached_network_image: ^3.3.1
  
  # Audio players
  audioplayers: ^6.1.0 

  # Camera (buat nyetor)
  camera: ^0.10.5

  permission_handler: ^11.3.0
  
  # Icons
  cupertino_icons: ^1.0.8

  # Local Video
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/Header.png
    - assets/images/Pelajari.png
    - assets/images/QuranMemo.png
    - assets/images/Riwayat-Hfl.png
    - assets/images/Setor.png
    - assets/images/self.jpg
    - assets/videos/